# luau
[language.luau.grammar.source.git]
url = "https://github.com/polychromatist/tree-sitter-luau"
pin = "0ed9b790c17c0097e13a4fcacda5818571786514"

[language.luau.grammar]
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.c", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "luau.so"]
link_flags = ["-O3"]

[language.luau.queries.source.git]
url = "https://github.com/polychromatist/tree-sitter-luau"
pin = "0ed9b790c17c0097e13a4fcacda5818571786514"

[language.luau.queries]
path = "helix-queries"
