colorscheme catppuccin-mocha

add-highlighter global/ number-lines -hlcursor -relative -separator " "
add-highlighter global/ show-matching
add-highlighter global/column-limit column 80 default,black+d

# highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

# using this just for indents since i keep near religious track of them
add-highlighter global/ show-whitespaces -spc ' ' -lf ' '

set-option global tabstop 8
set-option global indentwidth 0
set-option global scrolloff 0,3

set-option -add global ui_options terminal_status_on_top=true
set-option -add global ui_options terminal_assistant=none
set-option -add global ui_options terminal_set_title=no

# AUR kak doesn't have this option yet :(
# set-option -add global ui_options terminal_title='kak'

# jk to escape
hook global InsertChar k %{
	try %{
		exec -draft hH <a-k>jk<ret> d
		exec <esc>
	}
}
# tab 4 completion window
hook global InsertCompletionShow .* %{
	try %{
		execute-keys -draft 'h<a-K>\h<ret>'

		map window insert <tab> <c-n>
		map window insert <s-tab> <c-p>

		hook -once -always window InsertCompletionHide .* %{
			unmap window insert <tab> <c-n>
			unmap window insert <s-tab> <c-p>
		}
	}
}

# choosing which standard library stuff I want
nop %sh{
	# just checks if the symlink already exists and then symlinks it
	rc_import() {
		[ ! -e $kak_config/autoload/$2 ] && ln -s "$kak_runtime/rc/$1" "$kak_config/autoload/$2"
	}

	rc_import "windowing/tmux.kak" "tmux.kak"

	rc_import "tools/comment.kak" "comment.kak"
	rc_import "detection/file.kak" "file.kak"

	rc_import "filetype/sh.kak" "sh.kak"
	rc_import "filetype/kakrc.kak" "kakrc.kak"
	rc_import "filetype/lua.kak" "lua.kak"
	rc_import "filetype/asciidoc.kak" "asciidoc.kak"
	rc_import "filetype/odin.kak" "odin.kak"
	rc_import "filetype/toml.kak" "toml.kak"
	rc_import "filetype/json.kak" "json.kak"
}

# apparently grep automatically imports for you! how sweet!
require-module tmux

# vim reflexes
map global insert <c-w> '<esc>:execute-keys bd<ret>i'
map global insert <c-h> '<esc>:execute-keys hd<ret>i'

# i dont find much use on some of the default keys so here are my replacements!
map global normal <esc> ";,"
map global normal , "<a-i>"
map global normal . "<a-a>"
map global normal "'" "<a-;>"

map global normal m "<c-d>"
map global normal M "<c-u>"

map global normal q "[p"
map global normal e "]p"
map global normal Q "{p"
map global normal E "}p"

map global normal "z" '<a-.>'
map global normal "Z" '.'

# defined in autoload/god-mode.kak
map global normal v ':enter-user-mode god-mode-alt<ret>'
map global normal V ':enter-user-mode god-mode-hold-alt<ret>'

# for wsl
map -docstring 'copy to system clipboard' global user y '<a-|>clip.exe<ret>'
map -docstring 'comment line' global user c ':comment-line<ret>'

map -docstring 'open broot (filetree)' global user t ':tmux-terminal-window broot<ret>'
map -docstring 'open gitui' global user g ':tmux-terminal-window gitui<ret>'
map -docstring 'global find/replace' global user r ':tmux-terminal window rgr '

# imported from autoload/fuzzy.kak
map -docstring 'find files' global user f ':fuzzy-edit<ret>'
map -docstring 'global search/grep' global user s ':fuzzy-grep<ret>'
map -docstring 'buffer search' global user b ':fuzzy-buffer<ret>'

declare-user-mode window
map -docstring 'enter window mode' global user w ':enter-user-mode window<ret>'
map -docstring 'split vertical' global window s ':tmux-terminal-vertical kak -c %val{session}<ret>'
map -docstring 'split horizontal' global window v ':tmux-terminal-horizontal kak -c %val{session}<ret>'

# this mode will be edited in buffer scope by individual filetypes
declare-user-mode language
map -docstring 'enter language mode' global user l ':enter-user-mode language<ret>'
