file_watch_support = true
watch_file_support = true
snippet_support = false
verbosity = 2

[server]
# exit session if no requests were received during given period in seconds
# set to 0 to disable
timeout = 1800 # seconds = 30 minutes

# Semantic tokens support
# See https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_semanticTokens
# for the default list of tokens and modifiers.
# However, many language servers implement their own values.
# Make sure to check the output of `lsp-capabilities` and each server's documentation and source code as well.
# Examples:
# - TypeScript: https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/common/semanticTokens.ts
# - Rust Analyzer: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/syntax_highlighting.rs
[semantic_tokens]
faces = [
    {face="documentation", token="comment", modifiers=["documentation"]},
    {face="comment", token="comment"},
    {face="function", token="function"},
    {face="keyword", token="keyword"},
    {face="module", token="namespace"},
    {face="operator", token="operator"},
    {face="string", token="string"},
    {face="type", token="type"},
    {face="default+d", token="variable", modifiers=["readonly"]},
    {face="default+d", token="variable", modifiers=["constant"]},
    {face="variable", token="variable"},
]

[language_server.luau-lsp]
filetypes = ["luau"]
roots = ["aftman.toml", "default.project.json"]
command = "luau-lsp"
args = [
  "lsp",
  "--definitions",
  "/home/ivy/.local/share/kak/luau-lsp/globalTypes.d.luau",
  "--docs",
  "/home/ivy/.local/share/kak/luau-lsp/api-docs.json"
]

[language_server.luau-lsp.settings.luau-lsp]
[language_server.luau-lsp.settings.luau-lsp.editor]
formatOnSave = true

[language_server.luau-lsp.settings.luau-lsp.completion.imports]
enabled = true
suggestServices = true
suggestRequires = false

[language_server.typescript-language-server]
filetypes = ["javascript", "typescript"]
roots = ["package.json", "tsconfig.json", "jsconfig.json", ".git", ".hg"]
# yeah its janky but who cares
command = "npx"
args = ["typescript-language-server", "--stdio"]
settings_section = "_"

[language_server.typescript-language-server.settings._]
quotePreference = "double"
typescript.format.semicolons = "insert"
