[[language]]
name = "luau"
scope = "source.luau"
injection-regex = "^luau$"
file-types = ["luau"]
comment-token = "--"
indent = { tab-width = 8, unit = "  "}
language-servers = [ "luau-lsp" ]
roots = [ "aftman.toml", "default.project.json", "wally.toml" ]

[[grammar]]
name = "luau"
source = { git = "https://github.com/polychromatist/tree-sitter-luau", rev = "0ed9b790c17c0097e13a4fcacda5818571786514" }

[language-server.luau-lsp]
command = "luau-lsp"
args = [
  "lsp",
  "--definitions",
  "/home/ivy/.local/share/kak/luau-lsp/globalTypes.d.luau",
  "--docs",
  "/home/ivy/.local/share/kak/luau-lsp/api-docs.json"
]

[language-server.luau-lsp.config.editor]
formatOnSave = true

[language-server.luau-lsp.config.completion.imports]
enabled = true
suggestServices = true
suggestRequires = true
